apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-f9r8z
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.6.7"],"port":32100,"protocol":"TCP","serviceName":"data-servizi:organizations-nodeport","allNodes":true}]'
  creationTimestamp: 2018-05-15T15:42:50Z
  generation: 2
  labels:
    workload.user.cattle.io/workloadselector: deployment-data-servizi-organizations
  name: organizations
  namespace: data-servizi
  resourceVersion: "166995"
  selfLink: /apis/apps/v1beta2/namespaces/data-servizi/deployments/organizations
  uid: 9f75c4cd-5856-11e8-a87a-fa163edbfc14
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-data-servizi-organizations
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"organizations-nodeport","kind":"NodePort","name":"80tcp321001","protocol":"TCP","sourcePort":32100}]]'
        workload.cattle.io/state: '{"c3J2MDQtbWdy":"c-gpjbd:m-a4df351562d2"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-data-servizi-organizations
    spec:
      containers:
      - env:
        - name: MDBFCN
          value: mongodb://192.168.6.7:31534/organizations
        image: plunix/organizations
        imagePullPolicy: Always
        name: organizations
        ports:
        - containerPort: 80
          name: 80tcp321001
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeName: srv04-mgr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-05-15T15:42:53Z
    lastUpdateTime: 2018-05-15T15:42:53Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-05-15T15:42:50Z
    lastUpdateTime: 2018-05-15T15:42:53Z
    message: ReplicaSet "organizations-764d64c5f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

